# Meta Data for SEO

## Homepage
title = "Neutrino Oscillations"
titleSeparator = "-"
titleAddition = "Neutrino flavor oscillations in dense media"
description = "Neutrino flavor conversions in dense media play important roles in the physical and chemical evolutions of many dense environments."

## Open Graph + Twitter Cards
images = ["neutrinos.jpg"]
twitterSite = ""
twitterCreator = ""
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo.png"
schemaTwitter = ""
schemaLinkedIn = "https://www.linkedin.com/in/leima137/"
schemaGitHub = "https://github.com/emptymalei"
schemaSection = "book"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>. Made with Love by <a href=\"https://leima.is\">LM</a>"

# Alert
alert = true
alertText = "<a class=\"alert-link\" href=\"https://github.com/emptymalei/neutrino-oscillations/stargazers\">Star on GitHub</a>!</a> You may also be interested in <a class=\"alert-link\" href=\"http://neutrino.xyz\">neutrino.xyz</a>."

# Edit Page
docsRepo = "https://github.com/emptymalei/neutrino-oscillations"
editPage = true
